# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0831cf745f33988f6d6792aa911fc35be29c3cb35c4aeafaf461dae46b7e50afd2ee41873db53ccd48a0f5cb4ae8cbedcca7c7d586432c1bad77ef132b3d4db

test:
  secret_key_base: 9f6bca16dd6c0f45278f79e2c015e5c022061012d4ff54632fb688d6c5f7bab9b41dfe2b687f467048ed546b04bd9caff78eecf2c3455e1b401f3d9f161ff8a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
